# -*- makefile -*-
# Generated by aesmovie {version}.
#
# Include this from your Makefile between `include rom.mk` and
# `include build.mk`. It has to come before build.mk because it adds its
# own source directories to SRCDIRS, which build.mk reads.
#
#     include rom.mk
#     include fmv/fmv.mk
#     include build.mk

FMV_ROOT := $(patsubst %/,%,$(dir $(lastword $(MAKEFILE_LIST))))
FMV_SRC = $(FMV_ROOT)/{library_dir}
FMV_MOVIE = $(FMV_ROOT)/{movie_dir}

SRCDIRS += $(FMV_SRC) $(FMV_MOVIE)

# Which switchable bank the movie stream starts at. Raise it if your own
# banked code takes the low banks. The stream needs {stream_banks}
# consecutive bank(s), and the three-bit latch reaches banks 0 to 7.
FMV_FIRST_BANK ?= 0

# Set to anything but `yes` for a video-only build. Nothing then
# references a Z80 symbol, so your own sound driver keeps the M1 ROM.
FMV_AUDIO ?= {audio}

FMV_STREAM_BANKS = {stream_banks}
FMV_BANK_NUMBERS = {bank_numbers}

# Sizes the cartridge declaration needs, measured by the bake so nothing
# here has to be worked out by hand.
#
# FMV_CROM_BYTES already leaves room for your own tiles: the sprite ROM
# has to be a power of two, and the movie's dictionary rarely lands on
# one. FMV_FREE_TILES is how many slots that slack is worth.
FMV_TOTAL_BANKS = $(shell expr $(FMV_FIRST_BANK) + $(FMV_STREAM_BANKS))
FMV_ALL_BANK_NUMBERS = $(shell seq 0 $(shell expr $(FMV_TOTAL_BANKS) - 1))
FMV_PROM2_BYTES = $(shell expr $(FMV_TOTAL_BANKS) \* 1048576)
FMV_CROM_BYTES = {crom_size}
FMV_CROM_DICTIONARY_BYTES = {crom_payload}
FMV_FIRST_FREE_TILE = {tile_count}
FMV_FREE_TILES = {free_tiles}

FMV_CFLAGS = -I$(FMV_SRC) -I$(FMV_MOVIE)
FMV_LDFLAGS = -Wl,--defsym=fmv_stream_base=$(shell expr $(FMV_FIRST_BANK) \* 1048576)

FMV_OBJS = \
	$(BUILDDIR)/$(FMV_SRC)/fmv.o \
	$(BUILDDIR)/$(FMV_SRC)/timeline.o \
	$(BUILDDIR)/$(FMV_MOVIE)/movie_data_value.o \
	$(BUILDDIR)/$(FMV_MOVIE)/movie_data.o

ifeq ($(FMV_AUDIO),yes)
FMV_OBJS += $(BUILDDIR)/$(FMV_SRC)/fmv_audio.o
else
FMV_CFLAGS += -DFMV_NO_AUDIO
endif

FMV_BANK_OBJS = $(foreach bank,$(FMV_BANK_NUMBERS),\
	$(BUILDDIR)/$(FMV_MOVIE)/fmv_stream__bank$(bank).o)

# ngdevkit ships pattern rules for .c and .cc but none for m68k assembly,
# so the movie's .incbin stubs need one here.
$(BUILDDIR)/$(FMV_MOVIE)/%.o: $(FMV_MOVIE)/%.S
	$(M68KGCC) $(NGCFLAGS) $(CFLAGS) $(FMV_CFLAGS) -c $< -o $@

# A bank stub holds nothing but its slice of the stream. Every object
# gas emits also carries an empty .data, and for a __bank-named file the
# linkscript routes that into the bank-switched RAM segment, which turns
# .data2 into a loadable section and warns. Dropping the empty defaults
# leaves the object saying exactly what it is.
$(BUILDDIR)/$(FMV_MOVIE)/fmv_stream__bank%.o: $(FMV_MOVIE)/fmv_stream__bank%.S
	$(M68KGCC) $(NGCFLAGS) $(CFLAGS) $(FMV_CFLAGS) -c $< -o $@
	$(M68KOBJCOPY) -R .text -R .data -R .bss $@

# One ELF per switchable bank, which is the shape ngdevkit's linkscript
# wants: it keeps the __bank-named object out of the fixed megabyte and
# gathers it into .text2, and the cartridge rules turn each .text2 into
# one bank image.
#
# Set FMV_GAME_OBJS to your own objects before this file is included and
# the rules below are declared for you. Leave it empty and declare the
# ELF and PROM2 dependencies yourself.
#
# The second program ROM is the concatenation of its banks in the order
# they are named, so every bank below FMV_FIRST_BANK is named here too
# even though this file supplies no rule for one. That is what keeps a
# bank you own from landing at the wrong offset. Give each of yours a
# rule of the form
#
#     $(PROM2)_bank0: $(BUILDDIR)/my-banked-code.elf
ifneq ($(FMV_GAME_OBJS),)
$(foreach bank,$(FMV_BANK_NUMBERS),\
  $(eval $(BUILDDIR)/rom-fmv-bank$(bank).elf: $(FMV_GAME_OBJS) $(FMV_OBJS) \
    $(BUILDDIR)/$(FMV_MOVIE)/fmv_stream__bank$(bank).o)\
  $(eval $(PROM2)_bank$(shell expr $(FMV_FIRST_BANK) + $(bank)): \
    $(BUILDDIR)/rom-fmv-bank$(bank).elf))
$(foreach bank,$(FMV_ALL_BANK_NUMBERS),$(eval $(PROM2): $(PROM2)_bank$(bank)))
endif
